unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind r source-file $HOME/.tmux.conf

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
# Mac
set -s copy-command 'pbcopy'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'
# Linux
set -s copy-command 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1   
setw -g automatic-rename on
set -g renumber-windows on   

set -g mouse on

bind -r h select-window -t :-
bind -r l select-window -t :+
#bind -r k select-pane -U
#bind -r j select-pane -D

#The repeat timeout is controlled by repeat-time (default 500ms). You can increase it:
set -g repeat-time 1000

#set -g status-right '#{?client_prefix,#[bg=red] PREFIX ,} #{?pane_in_mode,#[bg=yellow] COPY ,}'
set -g status-left '#{?client_prefix,#[bg=red] PREFIX ,}#{?pane_in_mode,#[bg=yellow] COPY ,}'
set -g status-right '#(whoami)@#H - %H:%M:%S %d-%b  '
set -g status-right-length 500
set -g status-interval 1

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Run sessionizer script in a new pane
#bind z run-shell "$HOME/.local/share/tmux-sessionizer/tmux-sessionizer" --vsplit
#bind z run-shell "$HOME/software/dotfiles/scripts/tmux-sessionizer/tmux-sessionizer" --vsplit

